### ISSUE TITLE
SDL package linkage during build (Arch Linux)

### ISSUE THREAD

**Issue by n7st** [etorth/mir2x#11]
Hi,

It seems that my platform perhaps requires an extra package check statement to properly link the SDL2 libraries. Without it, `SDL2_INCLUDE_DIRS` and `SDL2_LIBRARIES` are empty:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c822ad33..ef87d3c6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -136,6 +136,7 @@ IF(WIN32)
     FIND_PACKAGE(FreeType REQUIRED)
 ELSE()
     FIND_PACKAGE(SDL2 REQUIRED)
+    pkg_check_modules(SDL2 REQUIRED sdl2)
 ENDIF()
 
 MESSAGE(STATUS "SDL2 found: SDL2_INCLUDE_DIRS: ${SDL2_INCLUDE_DIRS}, SDL2_LIBRARIES: ${SDL2_LIBRARIES}")
```

**Comment by wxyu247** [comment]
我也是arch，改了这里
client/src/CMakeLists.txt
`#    TARGET_LINK_LIBRARIES(client ${SDL2_LIBRARIES})
      TARGET_LINK_LIBRARIES(client SDL2::SDL2)`
