### ISSUE TITLE
Compilation failed ! 

### ISSUE THREAD

**Issue by fliot** [etorth/mir2x#14]
I suppose this is a simple dependency issue, but I didn't found what is missing, can you help me ?

<pre>[ 32%] <font color="#3465A4"><b>No install step for &apos;sol2&apos;</b></font>
[ 33%] <font color="#3465A4"><b>Completed &apos;sol2&apos;</b></font>
[ 33%] Built target sol2
<font color="#75507B"><b>Scanning dependencies of target mir2x_3rds</b></font>
[ 33%] Built target mir2x_3rds
<font color="#75507B"><b>Scanning dependencies of target common</b></font>
[ 33%] <font color="#4E9A06">Building CXX object common/src/CMakeFiles/common.dir/colorf.cpp.o</font>
<b>c++:</b> <font color="#CC0000"><b>error: </b></font>unrecognized command line option ‘<b>-fcoroutines</b>’
make[2]: *** [common/src/CMakeFiles/common.dir/build.make:63: common/src/CMakeFiles/common.dir/colorf.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1111: common/src/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:152: all] Error 2</pre>

**Comment by etorth** [comment]
update your gcc to gcc-10.2

**Comment by fliot** [comment]
indeed! Thanks
