### ISSUE TITLE
Client doesn't start

### ISSUE THREAD

**Issue by fliot** [etorth/mir2x#15]
Server is started, client fails, and I must confess I do not understand the reason.

<pre><font color="#3465A4"><b>~/GitHub/mir2x/b/install/client</b></font>$ ./client 
* This is the initialization of Log functionality
* For info/debug/warning/fatal messages.
* Log file: [/tmp/mir2x-client-v01.g3log.20210113-161520.log]
* Log functionality established!
* All messges will be redirected to the log after this line
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  100
  Current serial number in output stream:  101
g3log g3FileSink shutdown at: 16:15:20 713983
Log file at: [/tmp/mir2x-client-v01.g3log.20210113-161520.log]

<b>~/GitHub/mir2x/b/install/client</b></font>$ cat /tmp/mir2x-client-v01.g3log.20210113-161520.log
g3log g3FileSink shutdown at: 16:15:20 713983</pre>

**Comment by etorth** [comment]
This is not a mir2x error, it’s a X error.
Google a solution, either reboot, resinstall your gfx driver or whatever helps.

**Comment by fliot** [comment]
Indeed, it works after restart...
Great thanks for your patience, support and efficiency.
