### ISSUE TITLE
clang: fatal error: unknown argument: '-fcoroutines'

### ISSUE THREAD

**Issue by wikeyi** [etorth/mir2x#17]
[ 31%] Built target mir2x_3rds
[ 32%] Building CXX object common/src/CMakeFiles/common.dir/colorf.cpp.o
clang: fatal error: unknown argument: '-fcoroutines'
make[2]: *** [common/src/CMakeFiles/common.dir/build.make:63：common/src/CMakeFiles/common.dir/colorf.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1189：common/src/CMakeFiles/common.dir/all] 错误 2
make: *** [Makefile:152：all] 错误 2
root@wikeyi-Parallels-Virtual-Platform:~/mir2x/b# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.2.0-5ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-WJNXnb/gcc-10-10.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-WJNXnb/gcc-10-10.2.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Ubuntu 10.2.0-5ubuntu1~20.04)

**Comment by wikeyi** [comment]
gcc version 10.2.0 (Ubuntu 10.2.0-5ubuntu1~20.04) also failed

**Comment by etorth** [comment]
you need cmake with -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
