### ISSUE TITLE
test account can not login in.

### ISSUE THREAD

**Issue by winstonCN** [etorth/mir2x#21]
Hello, Etorth,

Thanks for your good project. i installed and started the game, but after learning "治愈术"，the client crashed, then i cannot not login in any more via 'test' account , any idea about the issue？
"Caught exception: In file skillboard.cpp:528, function: setMagicLevel: no magic icon for magic: 治愈术

**Comment by etorth** [comment]
currently supported magic as following.
All the rest are not supported yet, please delete install/server/mir2x.db3, and restart your server/client.

          {DBCOM_MAGICID(u8"雷电术"  ),  12,  78},
          {DBCOM_MAGICID(u8"魔法盾"  ), 252, 143},
          {DBCOM_MAGICID(u8"召唤骷髅"),  12,  13},
          {DBCOM_MAGICID(u8"召唤神兽"),  12,  78},
          {DBCOM_MAGICID(u8"灵魂火符"), 192,  13},
          {DBCOM_MAGICID(u8"冰月神掌"),  12,  13},
          {DBCOM_MAGICID(u8"冰月震天"),  12,  78},
          {DBCOM_MAGICID(u8"冰沙掌"  ), 132, 143},
          {DBCOM_MAGICID(u8"地狱火"  ), 132,  78},
          {DBCOM_MAGICID(u8"火球术"  ),  12,  13},
          {DBCOM_MAGICID(u8"大火球"  ),  12,  78},
          {DBCOM_MAGICID(u8"焰天火雨"),  12, 208},
          {DBCOM_MAGICID(u8"火墙"    ), 132, 143},
          {DBCOM_MAGICID(u8"疾光电影"), 132, 143},
