### ISSUE TITLE
no NPC name display 

### ISSUE THREAD

**Issue by winstonCN** [etorth/mir2x#22]
Hello, etorth

There is something wrong about display of npc name, even if i ran the client with --always-draw-name option, there is still no display. also the f'loating damage number is “+58”， “+8” which should be “-58”，“-8”.
could you please give some suggestions about the issue.
my environment is ubuntu os, any font need to be installed?

**Comment by etorth** [comment]
no, this is just because I haven't fix it yet, known issue.

**Comment by winstonCN** [comment]
ok，thanks

**Comment by etorth** [comment]
I will keep this open, the game is in very unfinished stage yet, so, many issues.
