### ISSUE TITLE
server launch exception bad_alloc

### ISSUE THREAD

**Issue by wikeyi** [etorth/mir2x#24]
`└─# cat /tmp/mir2x-monoserver-v01.g3log.20211105-095720.log 
                g3log created log at: Fri Nov 05 09:57:20 2021
                LOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL FILE->FUNCTION:LINE] message

                (uuu*: microseconds fractions of the seconds value)

2021/11/05 09:57:20 936691      INFO [actorpool.cpp->ActorPool:78]      Server FPS: 10
2021/11/05 09:57:24 451103      INFO [monoserver.cpp->createDefaultDatabase:360]        Create default sqlite3 database done
2021/11/05 09:57:24 451208      INFO [monoserver.cpp->CreateDBConnection:371]   Connect to database mir2x.db3 successfully
2021/11/05 09:57:24 461429      WARNING [main.cpp->main:125]    Exception in main thread: std::bad_alloc
                                       `

**Comment by etorth** [comment]
You need to install git-lfs to pull the resource files.
