### ISSUE TITLE
is the actor framework a third-party open-source software like "orca“ or implemented by yourself?

### ISSUE THREAD

**Issue by winstonCN** [etorth/mir2x#33]

**Comment by etorth** [comment]
A self-implemented one, you can check ```server/src/actorpool.cpp``` and ```server/src/actorpod.cpp```

I never test its performance, usually it ran 2w+ actors and looks fine, profiling shows no hotspot in actor framework.
There should be better framework for the actor model.

I was using theron but it looks dead.
