### ISSUE TITLE
关于使用zsdb打包资源的看法

### ISSUE THREAD

**Issue by Voyager1th** [etorth/mir2x#39]
// 对于PNG 文件 单个文件压缩是没有意义的，他本身就已经压缩过，所以再压缩反而使文件变大 更让资源加载变的更慢
我个人写了一个大包代码，只是简单的大包成一个文件，测试 proguse.zsdb 比压缩后还小3M

**Comment by etorth** [comment]
True, no point to compress single PNG.
Actually this class is still half done, I didn't pay much attention to it for a relative long time.

I planned to make PNGs compressed with dictionary.
Because most PNGs are small, but they shall some similarity, use a well-training dictionary shall help a lot.

**Comment by Voyager1th** [comment]
我想请教一下关于绘制地图上的问题，我用平滑移动方式绘图，但是绘制到建筑的影子的时候会出现阴影闪烁的问题，不知道是哪里问题
<img alt="绘制代码" src="http://cdn.vvxy.cn/downloads/code.png"/>
<http://cdn.vvxy.cn/downloads/demo.avi>

**Comment by etorth** [comment]
Can not access your video file.
But most likely same issue I used to see, not coding issue, I guess it's caused by screen resolution.

setup your monitor to lower resolution (800x600), then it will be good.
It's an old game.

**Comment by etorth** [comment]
I also saw this in other implementation.
My feeling is for sure it's not a coding issue, I don't have a good solution.

In mir2x I just de-mosaic by following function:

https://github.com/etorth/mir2x/blob/f31ce2a12dfa3fc64fb8e002f30562f964cbd43e/common/src/alphaf.hpp#L14

**Comment by Voyager1th** [comment]
谢谢，处理后效果好多了，但是还是有一些小块的闪烁，我再去想想办法完善一下。

**Comment by etorth** [comment]
> 谢谢，处理后效果好多了，但是还是有一些小块的闪烁，我再去想想办法完善一下。

My experience is if the project is still in its initial stage, I usually doesn't pay much attention to this kind of fine art things.

**Comment by Voyager1th** [comment]
是的，细节后面再完善，只是我每次测试的时候眼睛都快被闪瞎了，看代码都模糊了，所以就先处理一下，目前你的这套代码在Windows下画面很卡，尤其显示文本的窗口会让FPS掉到60以下，我不懂DX绘图这些，所以我的代码是用你的SDLDevice + IMGUI 写的，GT1030 显卡下 FPS也能到800左右

**Comment by etorth** [comment]
> 是的，细节后面再完善，只是我每次测试的时候眼睛都快被闪瞎了，看代码都模糊了，所以就先处理一下

oh you can compile and run with windows now ?

**Comment by etorth** [comment]
> 是的，细节后面再完善，只是我每次测试的时候眼睛都快被闪瞎了，看代码都模糊了，所以就先处理一下

I didn't optimize any for text print, slowing down is expected.
will work on it later, currently every character get rendered individually, pretty slow and naive.

**Comment by Voyager1th** [comment]
> 

是的我在Windows下编译成功了，但是 这套UI绘制文本有问题，FPS不到60，我借用了你的SDLDevice 自己重写了一套(我不懂DX这些，让你见笑了)。性能还可以，GT1030显卡下，FPS能到 800.
