### ISSUE TITLE
WSL编译libpinyin依赖问题

### ISSUE THREAD

**Issue by HaroldCC** [etorth/mir2x#41]
在编译的时候，需要依赖libpinyin，通过client目录下的CMakeLists.txt中的注释，我clone了libpinyin，并进行编译，但是后面make的时候出现找不到glib.h，我添加了glib-2.0，但是后面仍旧提示包含头文件错误，我的libpinyin或者glib库版本有问题？大佬能否告知应该选择那个版本的libpinyin或者glib库？
这是我的报错信息：
In file included from /usr/include/glib-2.0/glib/galloca.h:34,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/local/libpinyin/include/libpinyin-2.8.1/novel_types.h:29,
                 from /usr/local/libpinyin/include/libpinyin-2.8.1/pinyin.h:26,
                 from /mnt/f/Dev/mir2x/client/src/ime.cpp:8:
/usr/include/glib-2.0/glib/gtypes.h:34:10: fatal error: glibconfig.h: No such file or directory
   34 | #include <glibconfig.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [client/src/CMakeFiles/client.dir/build.make:566: client/src/CMakeFiles/client.dir/ime.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1369: client/src/CMakeFiles/client.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by etorth** [comment]
don't compile libpinyin yourself, it's so messy.
just do: sudo apt-get install libpinyin-dev

should be good enough.

**Comment by HaroldCC** [comment]
> don't compile libpinyin yourself, it's so messy. just do: sudo apt-get install libpinyin-dev
> 
> should be good enough.

编译通过了，多谢大佬

**Comment by renruiquan** [comment]
> 不要自己编译libpinyin，太乱了。只需做：sudo apt-get install libpinyin-dev
> 
> 应该足够好。

终于过了,一直报libpinyin的错误，使用sudo apt-get install libpinyin-dev亲测有效。
