### ISSUE TITLE
Deps questions

### ISSUE THREAD

**Issue by caryyu** [etorth/mir2x#47]
Sorry for bothering, I'm encountering some package missing issues, looks like we have to ensure every package being manually installed right?

![image](https://github.com/user-attachments/assets/011bdfb3-cadb-44d0-a027-92204dd0df80)
 

If so, do we have any plan to support the automatic dependency management? do you know any solutions for this, I guess this could mitigate the usage a lot.

**Comment by etorth** [comment]
Yes you need manually install.

**Comment by caryyu** [comment]
Got it, as I'm a newbie to CXX, do you have any knowledge about this dependency manager, like nuget in c#, maven in java and npm in js this kind of thing.
